### ISSUE TITLE
Jenkins Jobs with Markdown link check are failing

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/learning-labs-issues#255]
Here's output from a build.log file:

```
Started by timer
ENGIT Jenkins Usage Logger plugin has been loaded.
[EnvInject] - Loading node environment variables.
[EnvInject] - Preparing an environment for the build.
[EnvInject] - Keeping Jenkins system variables.
[EnvInject] - Keeping Jenkins build variables.
[EnvInject] - Injecting contributions.
Building remotely on sjc-wapl-bld65.cisco.com (slave65 CEL7.6 Linux cel7.6 rhel7 sjc vm3 RHEL7 docker) in workspace /bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci
using credential id_jenkins_learning_labs
Cloning the remote Git repository
Cloning repository git@github.com:CiscoDevNet/sbx-intro-aci.git
 > /usr/cisco/bin/git init /bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci # timeout=10
Fetching upstream changes from git@github.com:CiscoDevNet/sbx-intro-aci.git
 > /usr/cisco/bin/git --version # timeout=10
using GIT_SSH to set credentials SSH username with private key for GitHub.com
 > /usr/cisco/bin/git fetch --tags --progress git@github.com:CiscoDevNet/sbx-intro-aci.git +refs/heads/*:refs/remotes/origin/*
 > /usr/cisco/bin/git config remote.origin.url git@github.com:CiscoDevNet/sbx-intro-aci.git # timeout=10
 > /usr/cisco/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/cisco/bin/git config remote.origin.url git@github.com:CiscoDevNet/sbx-intro-aci.git # timeout=10
Fetching upstream changes from git@github.com:CiscoDevNet/sbx-intro-aci.git
using GIT_SSH to set credentials SSH username with private key for GitHub.com
 > /usr/cisco/bin/git fetch --tags --progress git@github.com:CiscoDevNet/sbx-intro-aci.git +refs/heads/*:refs/remotes/origin/*
 > /usr/cisco/bin/git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > /usr/cisco/bin/git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 84821e87e7593ee8bc06d8baf4baf7fb07d4956e (refs/remotes/origin/master)
 > /usr/cisco/bin/git config core.sparsecheckout # timeout=10
 > /usr/cisco/bin/git checkout -f 84821e87e7593ee8bc06d8baf4baf7fb07d4956e
Commit message: "Correct byod for CentOS Python install"
 > /usr/cisco/bin/git rev-list --no-walk 84821e87e7593ee8bc06d8baf4baf7fb07d4956e # timeout=10
No emails were triggered.
[markdown-link-check-sbx-intro-aci] $ /bin/sh -xe /bms/webapps/jenkins/jenkins3045431600850228896.sh
+ echo /bms/tools/node/node-v6.11.0-linux-x64/bin:/bms/tools/node/node-v6.11.0-linux-x64/bin:/usr/local/bin:/usr/bin:/orion/scripts:/bms/tools/bin:/bms/tools/bin:/bms/tools/bin:/bms/tools/bin
/bms/tools/node/node-v6.11.0-linux-x64/bin:/bms/tools/node/node-v6.11.0-linux-x64/bin:/usr/local/bin:/usr/bin:/orion/scripts:/bms/tools/bin:/bms/tools/bin:/bms/tools/bin:/bms/tools/bin
+ node --version
v6.11.0
+ which node
/bms/tools/node/node-v6.11.0-linux-x64/bin/node
+ npm --version
3.10.10
+ npm install markdown-link-check
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci
`-- markdown-link-check@3.8.1 
  +-- async@3.2.0 
  +-- chalk@4.0.0 
  | +-- ansi-styles@4.2.1 
  | | +-- @types/color-name@1.1.1 
  | | `-- color-convert@2.0.1 
  | |   `-- color-name@1.1.4 
  | `-- supports-color@7.1.0 
  |   `-- has-flag@4.0.0 
  +-- commander@5.1.0 
  +-- link-check@4.5.0 
  | +-- is-relative-url@3.0.0 
  | | `-- is-absolute-url@3.0.3 
  | +-- isemail@3.2.0 
  | | `-- punycode@2.1.1 
  | `-- ms@2.1.2 
  +-- lodash@4.17.15 
  +-- markdown-link-extractor@1.2.3 
  | `-- marked@0.8.2 
  +-- progress@2.0.3 
  `-- request@2.88.2 
    +-- aws-sign2@0.7.0 
    +-- aws4@1.10.0 
    +-- caseless@0.12.0 
    +-- combined-stream@1.0.8 
    | `-- delayed-stream@1.0.0 
    +-- extend@3.0.2 
    +-- forever-agent@0.6.1 
    +-- form-data@2.3.3 
    | `-- asynckit@0.4.0 
    +-- har-validator@5.1.3 
    | +-- ajv@6.12.2 
    | | +-- fast-deep-equal@3.1.1 
    | | +-- fast-json-stable-stringify@2.1.0 
    | | +-- json-schema-traverse@0.4.1 
    | | `-- uri-js@4.2.2 
    | `-- har-schema@2.0.0 
    +-- http-signature@1.2.0 
    | +-- assert-plus@1.0.0 
    | +-- jsprim@1.4.1 
    | | +-- extsprintf@1.3.0 
    | | +-- json-schema@0.2.3 
    | | `-- verror@1.10.0 
    | |   `-- core-util-is@1.0.2 
    | `-- sshpk@1.16.1 
    |   +-- asn1@0.2.4 
    |   +-- bcrypt-pbkdf@1.0.2 
    |   +-- dashdash@1.14.1 
    |   +-- ecc-jsbn@0.1.2 
    |   +-- getpass@0.1.7 
    |   +-- jsbn@0.1.1 
    |   +-- safer-buffer@2.1.2 
    |   `-- tweetnacl@0.14.5 
    +-- is-typedarray@1.0.0 
    +-- isstream@0.1.2 
    +-- json-stringify-safe@5.0.1 
    +-- mime-types@2.1.27 
    | `-- mime-db@1.44.0 
    +-- oauth-sign@0.9.0 
    +-- performance-now@2.1.0 
    +-- qs@6.5.2 
    +-- safe-buffer@5.2.1 
    +-- tough-cookie@2.5.0 
    | `-- psl@1.8.0 
    +-- tunnel-agent@0.6.0 
    `-- uuid@3.4.0 

npm WARN enoent ENOENT: no such file or directory, open '/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/package.json'
npm WARN markdown-link-check-sbx-intro-aci No description
npm WARN markdown-link-check-sbx-intro-aci No repository field.
npm WARN markdown-link-check-sbx-intro-aci No README data
npm WARN markdown-link-check-sbx-intro-aci No license field.
[markdown-link-check-sbx-intro-aci] $ /bin/bash /bms/webapps/jenkins/jenkins2403699609491145717.sh
# Find dead links in labs directory markdown files
find ./labs -name \*.md -exec ./node_modules/.bin/markdown-link-check {} \; > checklinks.txt
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/chalk/source/index.js:104
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/bms/webapps/jenkins/workspace/team_team_devnet-learning-labs-automation/markdown-link-check-sbx-intro-aci/node_modules/markdown-link-check/markdown-link-check:5:15)
date
Tue May 26 20:50:12 GMT 2020
cat checklinks.txt




Notifying upstream projects of job completion
Email was triggered for: Always
Sending email for trigger: Always
Sending email to: agentle@cisco.com smupadhy@cisco.com klevenst@cisco.com

```

**Comment by annegentle** [comment]
Alexey was able to get these fixed, closing issue.
